### ISSUE TITLE
Dynamic linking error: cannot locate symbol "fopen64"

### ISSUE THREAD

**Issue by millercl** [erlanger/swipl-termux#1]
After install script:
```
$ swipl
CANNOT LINK EXECUTABLE: cannot locate symbol "fopen64" referenced by "/data/data/com.termux/files/usr/lib/libswipl.so"...
page record for 0x7c481b010 was not found (block_size=14)
$ uname -m
aarch64
```
Some months ago, I built the swi-prolog source on-device referencing the [termux-packages](https://github.com/termux/termux-packages) upstream, but only after disabling all the prolog packages.

**Comment by erlanger** [comment]
Strange you get this error, because it wouldn't compile if the symbol was not in a library available at compile time. 

Unfortunately I don't have access to an aarch64 device to test, could you try installing directly from
the aarch64 .deb file and see if you get the same error?

Update: FYI, on a x86_64 android system we have fopen64:
```
$ nm -AD /system/lib/libc.so | grep fopen64
/system/lib/libc.so:000905c0 T fopen64
```
Can you run the same command on your system?

**Comment by millercl** [comment]
```
$ pkg install binutils
$ file /system/lib/libc.so
/system/lib/libc.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[md5/uuid]=1a7443b902961fdcecdb0f6cc0d3ebb5, not stripped
$ nm -AD /system/lib/libc.so | grep fopen64
# no lines
$ nm -AD /system/lib/libc.so | grep fopen
/system/lib/libc.so:0003a264 T fopen
$ nm -AD /system/lib/libc.so | grep fstat64
/system/lib/libc.so:000435cc T fstat64
$ git clone https://github.com/erlanger/swipl-termux.git
$ cd swipl-termux/debs
$ apt --fix-broken -y install ./ossp-uuid_1.6.2-2_aarch64.deb
# ...
$ apt --fix-broken -y install ./swi-prolog_8.1.0-1_aarch64.deb
# ...
$ which swipl
/data/data/com.termux/file/usr/bin/swipl
$ swipl
CANNOT LINK EXECUTABLE: cannot locate symbol "fopen64" referenced by "/data/data/com.termux/files/usr/lib/libswipl.so"...
page record for 0x1621924010 was not found (block_size=16)
```
Dynamic linking - so the symbol was available in the cross-compiling environment, but is not on the native environment? Strange because there are other `*64$` symbols.

**Comment by erlanger** [comment]
```
> $ file /system/lib/libc.so
> /system/lib/libc.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[md5/uuid]=1a7443b902961fdcecdb0f6cc0d3ebb5, not stripped
```
Yeah, the strange part is that your `/system/lib/libc.so` is a 32-bit version and yet, your architecture is `aarch64`. This is why it is failing.

The termux `libc` library used to cross-compile   for `aarch64`   is a 64bit version:

```
builder@6978f0f37e22:~/.termux-build/_cache/18-aarch64-21-v1$ file ./sysroot/usr/lib/libc.so
./sysroot/usr/lib/libc.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[md5/uuid]=6e242963b558adf712ae2da55ae9102c, with debug_info, not stripped
```

I would think something went wrong with your installation, perhaps `libc.so` was mistakenly overwritten by some app with root privileges. Can you try finding a stock android aarch64 device and compare its `libc.so`? I would expect it to be a 64-bit version.

**Comment by erlanger** [comment]
Another thing to try:
Recompile termux SWI-Prolog with `export CFLAGS=${CFLAGS} -DUSE_FILE32API` before running the build script in the docker container.
This might solve your problem.

Update: I looked at the `libc.so` on the `x86_64` android emulator, and it is also a 32bit version! Strange. Let me know if the above recompilation works for you. I am considering defining -DUSE_FILE32API for both 64 and 32bit (right now it is only enabled for 32bit) but I need you to recompile and let me know if it works for you.

Update2: There is a also `/system/lib64/libc.so` which is 64-bit and it has `fopen64`:
```
$ nm -AD /system/lib64/libc.so|grep fopen
/system/lib64/libc.so:0000000000088e90 T fopen
/system/lib64/libc.so:0000000000088e90 T fopen64
```
I wonder why the linker is using the `/system/lib/libc.so` instead of `/system/lib64/libc.so`.

**Comment by erlanger** [comment]
probably working now. closing.
