### ISSUE TITLE
swipl-termux issue: version 8.1.3 (threaded, 32bits): test(s) failed.

### ISSUE THREAD

**Issue by ringkern** [erlanger/swipl-termux#3]
swipl-termux issue: version 8.1.3 (threaded, 32bits): test(s) failed.

Hi Erlanger,
I started trying swipl-termux on my android arm devices when I read about it a week ago or so,
it looks very interesting and useful.

Version 8.1.2 would install but give an effectively fatal error, this is attached.

Fortunately, 8.1.3 installs and runs fine but fails at least 1 test.
I tried on 4 different android devices (running android 6.01, 6.01, 7.1.2, 8.1.0) using termux-0.66.
The log from android 8.1.0 is also attached.

On all 4 systems the following errors occur: (these are the only errors for android 7.1.2)
- assert/1: No permission to modify static procedure `test_module:cross/1' 
- Script /data/data/com.termux/files/usr/lib/swipl/test/Tests/GC/test_clause_gc.pl failed: Stack limit (1.9Mb) exceeded 

On both android 6.0.1 and 8.1.0 the following error occurs:
- Running test set "gmp" .....................[Thread 1]: global-overflow: spare=0 (def=2048) 
  Last resource exception:
  /home/builder/.termux-build/swi-prolog/src/src/os/pl-cstack.c:992 C-stack dumps are not supported on this platform 

And on 8.1.0 there is an additional problem with pengines:
- Script test_pengines.pl failed: Unknown message: killed(6)

I tested with:
`swipl -t 'time(test_installation)' 2>&1 | tee aokp-8.1.0--swipl-8.1.3.txt`

I am eager to try testing with the latest stable swipl-termux-7.??? but could not find it...
Maybe noteworthy: all my android systems run custom roms without G*gl? Apps.

[swipl-termux-8.1.2-readline_error.txt](https://github.com/erlanger/swipl-termux/files/2985141/swipl-termux-8.1.2-readline_error.txt)
[aokp-8.1.0--swipl-8.1.3.txt](https://github.com/erlanger/swipl-termux/files/2985169/aokp-8.1.0--swipl-8.1.3.txt)

**Comment by erlanger** [comment]
Hi ringkern,

   thanks for the tests!

* **Readline error**: this is fixed in 8.1.3 build for Android.
* **No permission to modify static procedure `test_module:cross/1'**: this is not really a major error, it happens in all platforms (even non android) should be fixed sometime upstream, but don't worry about it, it doesn't affect the running system. It is most likely a naming issue of some new tests that are being added upstream.

* **Stack limit exceeded** : this means you ran out of memory, this happens some times when memory is low.

* **gmp - global overflow**: have never seen this one, but could be related to the memory problem in the previous item.

* **pengines - killed(6)** : this means the Android OS killed a thread forcefully because it was trying to reclaim resources. Sadly Android is not being very gentle in later versions, it is turning unix upside-down by changing many things people have come to expect from Unix. Nonetheless this error is rare, it happens only because pengines test starts many threads.

**Comment by ringkern** [comment]
Ok erlanger, thanks for the point-wise explanation, these devices are all somewhat dated
(1GB RAM except for the android-8.1.0, that one has 1.5GB).
Very glad to hear they are not gamebreakers as long as the sparse resources are sensibly managed...

On to the next issue...
