### ISSUE TITLE
swipl-8.1.3-arm: no help system

### ISSUE THREAD

**Issue by ringkern** [erlanger/swipl-termux#4]
Hi erlanger, I got my test project working on arm device (originally swipl-win) after solving utf8 encoding problem and completely switching to unix (LF) line endings.

Then I started doc_server/2 but could not find proper index.
Then I tested help:

_"$ swipl
Welcome to SWI-Prolog (threaded, 32 bits, version 8.1.3)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.
For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).
?- apropos(help).
ERROR: Undefined procedure: apropos/1 (DWIM could not correct goal)
?- help(apropos).
ERROR: Undefined procedure: help/1 (DWIM could not correct goal)"_

So, is the help system missing intentionally? Can I or you add it?
I really would like to use the full help system...

**Comment by erlanger** [comment]
Hi @ringkern, 

Yes, it is built without the documentation on purpose, because the resources in android devices are rather scarce.

What I do, and I recommend you do this too is to open the http://www.swi-prolog.org/pldoc/man?section=builtin on a browser and keep it open, then you can search in the top right hand corner.

On the other hand, if you have docker installed (on a desktop/laptio) you could change the `build.sh` script and change `-DINSTALL_DOCUMENTATION=OFF` to `-DINSTALL_DOCUMENTATION=ON` and rebuild the package. It is a bit of work to build it, but there are some instructions in the main page, but I would rather recommend the browser option, because the help(..) text system is new and is missing a few predicates.

**Comment by ringkern** [comment]
Hi @erlanger,
thanks for the explanation.
If possible / feasible, I prefer offline / standalone setups.
Since I have 2 almost identical tablets, I could try building_with_docs and then install that on one of them, esp. for the doc system and use the other one "for real".
I have not worked with docker before but did read about it, so when I'm feeling courageous I might have a go at it. I greatly appreciate your efforts for this project.

You state "...help(..) text system is new and is missing a few predicates.".
Any idea how to find out which ones are missing?

**Comment by erlanger** [comment]
Hi ringkern,

   You can run the website offline/standalone by installing it from: https://github.com/SWI-Prolog/plweb (see the README there), you could run this on a local machine in your lan and then access it from your tablet.

As far as how to find out what predicates are missing from `help(...)`, I don't have any method. By experience I know some predicates exist, and I found out they are missing from the `help(...)` system, like `read_line_to_string/2`. They are not many, and should be fixed soon.

**Comment by ringkern** [comment]
Hi @erlanger,

I looked up the plweb README, it looks doable. What I do not understand is point 2:
`For a full installation, install the dynamic data.`
Where / how to get that? Can't find references anywhere.
I presume it refers to existing data, not auto-generated data.
Beginner misunderstanding? (I have no previous experience with this kind of thing)

**Comment by erlanger** [comment]
Hi @ringkern,

   Don't worry about the dynamic data, you don't need the wiki and the other stuff for a full installation.
   BTW, another --easier-- way to see the documentation is to install SWIProlog in some other non-android     machine and run `doc_browser`.

**Comment by ringkern** [comment]
Hi @erlanger,

ok, I won't worry, enough solutions to try.
**( ͡° ͜ʖ ͡°)** Thanks for your help! **( ͡° ͜ʖ ͡°)**

**Comment by ringkern** [comment]
Hi again @erlanger,

on rethinking, since you already have a *working* docker/compilation setup, could you please make available a version with `-DINSTALL_DOCUMENTATION=ON`? For you it shouldn't be any trouble since you have the setup already, for me it would be a separate new project :( no docker xp yet) and much more difficult.
    I will test  its "workability" on my relatively ancient p5100 tablet and report back about (lack of) performance and memory hogging.
    The best I can hope for would be a working doc_server + help_system + ability_to_run_simple_stuff; the worst would be that enabling the help sytem would lame my tablet entirely.
    I am not averse to testing this, but maybe you tried already and discarded it... I don't know...

**Comment by erlanger** [comment]
Hi Ringkern,

   I don't really want to maintain two separate releases, especially when the documentation is so easily available on the website (I myself keep the docs open in a browser); the main reason why I didn't build it with documentation is not because of runtime performance, but because it increases the storage requirement in the android devices, and the documentation is a space hog in such a small device.

**Comment by ringkern** [comment]
Hi @erlanger , ok, understood.
